# Generated by Django 4.2.7 on 2025-01-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_studentprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"ordering": ["-post__created_at"]},
        ),
        migrations.AddField(
            model_name="blogpost",
            name="category",
            field=models.CharField(
                choices=[
                    ("tech", "Technology"),
                    ("lifestyle", "Lifestyle"),
                    ("education", "Education"),
                    ("sports", "Sports"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="read_time",
            field=models.IntegerField(default=5),
        ),
    ]
