# Generated by Django 4.2.7 on 2025-01-12 06:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_blogpost_options_blogpost_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={},
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="category",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="featured_image",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="read_time",
        ),
    ]
