# Generated by Django 4.2.7 on 2025-01-12 07:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_category_course_coursecontent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="category",
        ),
        migrations.RemoveField(
            model_name="coursecontent",
            name="course",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="CourseContent",
        ),
    ]
