# Generated by Django 5.1.1 on 2025-03-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_team_teammember"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmember",
            name="is_core_team",
            field=models.BooleanField(default=False),
        ),
    ]
