# Generated by Django 5.1.1 on 2025-03-03 07:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_clubquestion_clubanswer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clubquestion",
            name="asked_by",
        ),
        migrations.RemoveField(
            model_name="clubquestion",
            name="club",
        ),
        migrations.DeleteModel(
            name="ClubAnswer",
        ),
        migrations.DeleteModel(
            name="ClubQuestion",
        ),
    ]
