# Generated by Django 5.1.1 on 2025-03-11 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacultyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="faculty_pics/"),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculty_members",
                        to="accounts.clubprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
